image:
- Ubuntu

configuration: Release

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

before_build:
- ps: |-
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud

build:
  publish_nuget: true
